class Driver:
    def __init__(self, *, db_path, rootdir, reserved_space, client_cfg, ftp_cfg, job_queue):
        self.ftp_enabled = ...

    def get_whitelist(self):
        ...

    def whitelist_user(self, user):
        ...

    def get_speed_limits(self):
        ...

    def get_disk_usage(self):
        ...

    def share_root_ftp(self):
        ...

    def unshare_root_ftp(self):
        ...
